In [1]:
import chardet
import pandas as pd
import glob as gb

file_pattern = 'C:\\Users\\andriel24044\\Downloads\\2024\\*.csv'
lista = gb.glob(file_pattern)

with open('INMET_SE_MG_F501_BELO HORIZONTE - CERCADINHO_01-01-2024_A_30-04-2024.csv', 'rb') as f:
    result = chardet.detect(f.read())

print(result['encoding'])

ISO-8859-1

In [2]:
import os

os.getcwd()

'C:\\Users\\andriel24044\\Downloads\\2024'

In [4]:
for i in lista:
    with open(i, 'r', encoding='ISO-8859-1') as file:
        data = file.read()

    data_corrigida = data.replace(',', '.')

    with open(i, 'w', encoding='ISO-8859-1') as file:
        file.write(data_corrigida)

In [28]:
temp = pd.read_csv('INMET_SE_MG_F501_BELO HORIZONTE - CERCADINHO_01-01-2024_A_30-04-2024.csv', encoding = 'ISO-8859-1', skiprows = 8, delimiter = ';', index_col = 'Data')
temp.head()

,Hora UTC,PRECIPITAÇÃO TOTAL. HORÁRIO (mm),PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO. HORARIA (mB),PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),TEMPERATURA DO AR - BULBO SECO. HORARIA (°C),TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),UMIDADE RELATIVA DO AR. HORARIA (%),VENTO. DIREÇÃO HORARIA (gr) (° (gr)),VENTO. RAJADA MAXIMA (m/s),VENTO. VELOCIDADE HORARIA (m/s),Unnamed: 19
Data,,,,,,,,,,,,,,,,,,,
2024/01/01,0000 UTC,0.0,880.7,881.0,880.7,0.1,18.5,17.0,19.1,18.5,17.5,17.0,91,91,91,135,15.7,10.8,NaN
2024/01/01,0100 UTC,0.0,881.3,881.3,880.6,0.0,18.4,16.9,18.5,18.4,16.9,16.9,91,91,91,129,15.5,9.8,NaN
2024/01/01,0200 UTC,0.0,881.6,881.7,881.3,0.0,18.2,16.7,18.4,18.2,16.9,16.7,91,91,91,125,13.8,10.5,NaN
2024/01/01,0300 UTC,0.0,881.6,881.8,881.4,0.0,18.1,16.6,18.2,18.1,16.7,16.6,91,91,91,124,13.3,7.5,NaN
2024/01/01,0400 UTC,0.4,881.5,881.7,881.5,0.0,18.1,16.6,18.1,18.0,16.6,16.5,91,91,91,135,9.9,4.6,NaN

In [29]:
#temp = temp[["TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)"]]
#print(temp)
temp = temp.iloc [:,[0,1,5,8,9,14,15,16]]

In [30]:
temp.head()

,Hora UTC,PRECIPITAÇÃO TOTAL. HORÁRIO (mm),RADIACAO GLOBAL (Kj/m²),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),UMIDADE RELATIVA DO AR. HORARIA (%),VENTO. DIREÇÃO HORARIA (gr) (° (gr)),VENTO. RAJADA MAXIMA (m/s)
Data,,,,,,,,
2024/01/01,0000 UTC,0.0,0.1,19.1,18.5,91,135,15.7
2024/01/01,0100 UTC,0.0,0.0,18.5,18.4,91,129,15.5
2024/01/01,0200 UTC,0.0,0.0,18.4,18.2,91,125,13.8
2024/01/01,0300 UTC,0.0,0.0,18.2,18.1,91,124,13.3
2024/01/01,0400 UTC,0.4,0.0,18.1,18.0,91,135,9.9

In [32]:
temp['Hora UTC'] = pd.to_datetime(temp['Hora UTC'], format='%H%M UTC')

# Criar uma nova coluna para representar os períodos do dia
def periodo_do_dia(hora):
    if hora.hour < 6:
        return '00:00 às 06:00'
    elif hora.hour < 12:
        return '06:00 às 12:00'
    elif hora.hour < 18:
        return '12:00 às 18:00'
    else:
        return '18:00 às 24:00'

temp['Periodo do Dia'] = temp['Hora UTC'].apply(periodo_do_dia)

# Agrupar os dados por períodos do dia e calcular a média
media_por_periodo = temp.groupby('Periodo do Dia').mean()

media_por_periodo.head()

,Hora UTC,PRECIPITAÇÃO TOTAL. HORÁRIO (mm),RADIACAO GLOBAL (Kj/m²),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),UMIDADE RELATIVA DO AR. HORARIA (%),VENTO. DIREÇÃO HORARIA (gr) (° (gr)),VENTO. RAJADA MAXIMA (m/s)
Periodo do Dia,,,,,,,,
00:00 às 06:00,1900-01-01 02:30:00,0.270248,0.026171,20.298209,19.688154,81.056474,133.769972,8.613223
06:00 às 12:00,1900-01-01 08:30:00,0.206061,172.126171,19.680165,18.788017,82.692837,127.418733,8.132782
12:00 às 18:00,1900-01-01 14:30:00,0.162810,2171.023003,26.140496,23.495730,61.001377,171.695592,7.308678
18:00 às 24:00,1900-01-01 20:30:00,0.653168,645.347521,24.360055,22.568871,67.013774,156.140496,7.994628

In [ ]:
null_pct = temp.apply(pd.isnull).sum()/temp.shape[0]

In [ ]:
temp.shape

In [ ]:
null_pct

In [ ]:
colunas_validas = temp.columns[null_pct < .05]

In [ ]:
colunas_validas

In [ ]:
temp = temp[colunas_validas].copy()

In [ ]:
temp.columns = temp.columns.str.lower()

In [ ]:
temp = temp.ffill()

In [ ]:
temp.apply(pd.isnull).sum()

In [ ]:
temp.dtypes

In [ ]:
temp.index

In [ ]:
temp.index = pd.to_datetime(temp.index)

In [ ]:
temp.index.year.value_counts().sort_index()

In [ ]:
temp.columns

In [ ]:
temp.head()

In [ ]:
temp["precipitação total. horário (mm)"].plot()

In [ ]:
import pandas as pd
from matplotlib import pyplot as plt
import scipy.stats as stats
import numpy as np
import seaborn as sns

In [ ]:
print(temp.shape)
print(temp.info())
print(temp.describe(include='all'))

In [ ]:
#temp = temp.drop_duplicates(['Data'], keep='first')
#print(temp.shape)

In [ ]:
sns.set(rc={'figure.figsize':(20,8)}, style='whitegrid')
sns.boxplot(data=temp['pressão atmosferica min. na hora ant. (aut) (mb)'])